# fly.toml app configuration file generated for seniorjob on 2025-11-20T15:59:45+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seniorjob'
primary_region = 'nrt'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.http_check]
    interval = "15s"
    timeout = "10s"
    grace_period = "120s"
    method = "GET"
    path = "/actuator/health"
    protocol = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  # 환경변수 설정
  DATABASE_URL = "jdbc:postgresql://planadb.internal:5432/postgres"
  DB_USERNAME = "postgres"